/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef gPTP_S32K3xx_H
#define gPTP_S32K3xx_H



#endif /* gPTP_S32K3xx_H */
